version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/hypertube
      - TRANSMISSION_HOST=transmission
      - TRANSMISSION_PORT=9091
      - OMDB_API_KEY=e5ee17b5
    depends_on:
      - db
      - transmission
    volumes:
      - downloads:/downloads
    command: npm run start:prod

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3000
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: npm run dev

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - USER=admin
      - PASS=admin123
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - transmission_config:/config
      - downloads:/downloads
      - downloads:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hypertube
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  downloads:
  transmission_config: